# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=50, verbose_name='Telefono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('administrativos', models.ManyToManyField(related_name='administrativos', through='escuelas.Administrativos', to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(verbose_name='Admision')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='Salida')),
                ('idEscuelaRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelasE', to='escuelas.Escuela', verbose_name='Escuela')),
                ('idPersonaRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personasE', to='personas.Persona', verbose_name='Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEscuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='escuela',
            name='estudiantes',
            field=models.ManyToManyField(related_name='estudiantes', through='escuelas.Estudiantes', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='idDistritoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lugares.Distrito', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='escuela',
            name='idTipoEscuelaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escuelas.TipoEscuela', verbose_name='Tipo de escuela'),
        ),
        migrations.AddField(
            model_name='administrativos',
            name='idEscuelaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelasA', to='escuelas.Escuela', verbose_name='Escuela'),
        ),
        migrations.AddField(
            model_name='administrativos',
            name='idPersonaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personasA', to='personas.Persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='administrativos',
            name='idPuestoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos', to='escuelas.Puesto', verbose_name='Puesto'),
        ),
    ]
