# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativos',
            name='telefono',
            field=models.CharField(max_length=30, verbose_name='Telefono'),
        ),
    ]
