# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0003_auto_20170405_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativos',
            name='idEscuelaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelas_administrativos', to='escuelas.Escuela', verbose_name='Escuela'),
        ),
        migrations.AlterField(
            model_name='administrativos',
            name='idPersonaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas_administrativos', to='personas.Persona', verbose_name='Persona'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='idEscuelaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelas_estudiantes', to='escuelas.Escuela', verbose_name='Escuela'),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='idPersonaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas_estudiantes', to='personas.Persona', verbose_name='Persona'),
        ),
    ]
