# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('personas', '0006_persona_fotos'),
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('corto', models.CharField(max_length=50, unique=True, verbose_name='Corto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('fecha', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Nombre')),
                ('fechaInicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(default=datetime.date.today, verbose_name='Fecha de fin')),
                ('lugar', models.CharField(max_length=100, verbose_name='Nombre del lugar')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('latitud', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=30, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=30, null=True, verbose_name='Longitud')),
                ('logos', models.ImageField(upload_to='logos/programas/', verbose_name='Logo')),
                ('capacitadores', models.ManyToManyField(db_table='Capacitadores', related_name='capacitadores', to='personas.Persona')),
                ('galeria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galeria')),
                ('idDistritoRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lugares.Distrito', verbose_name='Distrito')),
                ('mentores', models.ManyToManyField(db_table='Mentores', related_name='mentores', to='personas.Persona')),
            ],
        ),
    ]
