# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(editable=False, max_length=100, unique=True, verbose_name='Nombre')),
                ('fechaInicio', models.DateField(default=datetime.date.today, verbose_name='Fecha de inicio')),
                ('fechaFin', models.DateField(default=datetime.date.today, verbose_name='Fecha de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('mentores', models.ManyToManyField(db_table='Mentores', to='personas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='periodo',
            name='idProgramaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programas.Programa', verbose_name='Programa'),
        ),
    ]
