# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170421_0327'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa',
            old_name='logos',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='programa',
            name='patrocinadores',
            field=models.ManyToManyField(db_table='Patrocinadores', related_name='patrocinadores', to='home.Tercero'),
        ),
    ]
