# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('personas', '0006_persona_fotos'),
        ('home', '0003_tercero'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='capacitadores',
            field=models.ManyToManyField(db_table='Capacitadores', related_name='capacitadores', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='programa',
            name='galeria',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galeria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='logo',
            field=models.ImageField(default=0, upload_to='logos/programas/', verbose_name='Logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='patrocinadores',
            field=models.ManyToManyField(db_table='Patrocinadores', related_name='patrocinadores', to='home.Tercero'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='mentores',
            field=models.ManyToManyField(db_table='Mentores', related_name='mentores', to='personas.Persona'),
        ),
    ]
