# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20170421_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='fecha',
        ),
    ]
