# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('personas', '0006_persona_fotos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('facilitadores', models.ManyToManyField(related_name='facilitadores', through='sesiones.Facilitadores', to='personas.Persona')),
                ('idProgramaRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programas.Programa', verbose_name='Programa')),
                ('participantes', models.ManyToManyField(db_table='Participantes', related_name='participantes', to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('inicio', models.TimeField(default=datetime.date.today, verbose_name='Hora de inicio')),
                ('fin', models.TimeField(default=datetime.date.today, verbose_name='Hora de fin')),
                ('idPrograma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programas.Programa', verbose_name='Programa')),
            ],
            options={
                'verbose_name': 'Sesion',
                'verbose_name_plural': 'Sesiones',
            },
        ),
        migrations.CreateModel(
            name='TipoFacilitador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='facilitadores',
            name='idGrupoRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_facilitadores', to='sesiones.Grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='facilitadores',
            name='idPersonaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas_facilitadores', to='personas.Persona', verbose_name='Persona'),
        ),
        migrations.AddField(
            model_name='facilitadores',
            name='idTipoFacilitadorRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sesiones.TipoFacilitador', verbose_name='Tipo de facilitador'),
        ),
    ]
