# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20170318_0009'),
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='facilitadores',
            field=models.ManyToManyField(db_table='Facilitadores', to='personas.Persona'),
        ),
    ]
