# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0005_auto_20170318_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('idPersonaRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.Persona', verbose_name='Persona')),
            ],
        ),
    ]
