# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIntegrante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='idTipoIntegranteRef',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='home.TipoIntegrante', verbose_name='Tipo integrante'),
            preserve_default=False,
        ),
    ]
