# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170408_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='Direccion web')),
                ('logo', models.ImageField(upload_to='logos/terceros/', verbose_name='Logo')),
            ],
        ),
    ]
