# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170421_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('informacion', redactor.fields.RedactorField(verbose_name='Informacion')),
                ('actualizacion', models.DateTimeField(default=datetime.datetime(2017, 4, 22, 6, 39, 32, 716484, tzinfo=utc), verbose_name='Ultima actualizacion')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
        migrations.AlterField(
            model_name='acerca',
            name='actualizacion',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 6, 39, 32, 715972, tzinfo=utc), verbose_name='Ultima actualizacion'),
        ),
    ]
