# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('idCantonRef', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lugares.Canton', verbose_name='Canton')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='idProvinciaRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lugares.Provincia', verbose_name='Provincia'),
        ),
    ]
