# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('apellido2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Segudo apellido')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=5, verbose_name='Sexo')),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha nacimiento')),
                ('celular', models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True, verbose_name='Celular')),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=30, verbose_name='Telefono')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
