# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido1',
            field=models.CharField(default='', max_length=50, verbose_name='Primer apellido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono'),
        ),
    ]
