# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20170315_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Identificacion'),
            preserve_default=False,
        ),
    ]
