# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20170317_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fechaNacimiento',
            new_name='fecha',
        ),
    ]
