# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 03:38
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('personas', '0005_auto_20170318_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fotos',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, related_name='fotos', to='photologue.Photo'),
        ),
    ]
